# Generated by Django 5.2.14 on 2026-06-08 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('data', models.BinaryField()),
                ('content_type', models.CharField(default='image/jpeg', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, unique=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='interest_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='max_age_pref',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='profile',
            name='max_distance_km',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='min_age_pref',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='profile',
            name='relationship_type',
            field=models.CharField(blank=True, choices=[('casual', 'Casual / Dating'), ('serious', 'Serious Relationship'), ('friends', 'Friends First'), ('undecided', 'Not Sure Yet')], max_length=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='wants_kids',
            field=models.CharField(blank=True, choices=[('yes', 'Want kids'), ('no', "Don't want kids"), ('open', 'Open to it'), ('has', 'Already have kids')], max_length=10),
        ),
        migrations.CreateModel(
            name='UserPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('answer', models.CharField(max_length=300)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.prompt')),
            ],
            options={
                'unique_together': {('user_id', 'prompt')},
            },
        ),
    ]
